Add cmdlet Get-CWMCompanyConfigurationTypes
christaylorcodes/ConnectWiseManageAPI pull request #13
Opened 2021-04-20 10:23 UTC by ionise

Lets you return a list of configuration types without needing to leave powershell 
For example:
Get-CWMCompanyConfigurationTypes -Condition 'name contains "Managed"' -all 
…will return all the configuration types that contain the name "Managed"

2021-04-29 04:28 UTC, ionise commented on ConnectWiseManageAPI/Public/System/Documents/New-CWMDocument.ps1
> +
I'd argue that in this instance the line break after this parameter definition makes it easier to see where this parameter finishes and the next one begins.

2021-04-30 05:15 UTC, christaylorcodes requested changes
Please submit with all parameters available in the documentation. 
Please validate max string length where applicable.

2021-05-02 22:09 UTC, ionise reviewed
> Please submit with all parameters available in the documentation.
> Please validate max string length where applicable.

https://developer.connectwise.com/Products/Manage/REST#/Documents/postSystemDocuments ...
Does not specify any mandatory parameters or max string lengths.

https://developer.connectwise.com/Products/Manage/REST#/Configurations/postCompanyConfigurations ..
I have added all available parameters (except ID since that is probably best left for the system to generate automatically for new configuration items) 
"name" appears to be the only mandatory parameter in the API, but in the function I have made "type" and "company" mandatory also. 

TODO: 

- Add new cmdlets to FunctionsToExport= in ConnectWiseManageAPI.ps1:  get-CWMCompanyConfigurationTypes new-CWMCompanyConfiguration
- Write new documentation for get-CWMCompanyConfigurationTypes.ps1
- Write new documentation for new-CWMCompanyConfiguration.ps1
- Update documentation for new-CWMDocument.ps1

Is there a generator for the initial creation of a document for each cmdlet or shall I just grab an existing one as a template and modify it by hand?

2021-05-02 22:09 UTC, ionise commented on ConnectWiseManageAPI/Public/System/Documents/New-CWMDocument.ps1
> +            If(!$FileName){
This If block used to be in a validationscript block in the Param section, but it would break the URL parameter set because it was not using the $Filepath parameter even though this parameter was not required for the URL parameter set. It might be neater if it was back in the Param section if anybody can figure out a way to allow it to be null, but only if the URL parameter set is being used.

2021-05-05 03:38 UTC, merged